exclude = []
line-length = 120
indent-width = 2

[lint]
select = ["F", "I", "UP"]
ignore = []
fixable = ["ALL"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
