"""Added transactions table

Revision ID: 2c4b0771311a
Revises: a46ee198495e
Create Date: 2025-05-19 20:10:04.907576

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c4b0771311a"
down_revision: Union[str, None] = "a46ee198495e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "transactions",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("account_mapping_id", sa.Uuid(), nullable=False),
    sa.Column("pluggy_transaction_id", sa.Uuid(), nullable=False),
    sa.Column("ynab_transaction_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("transaction_date", sa.DateTime(), nullable=False),
    sa.Column("amount", sa.Float(), nullable=False),
    sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("synced_at", sa.DateTime(), nullable=True),
    sa.Column("raw_transaction", sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(
      ["account_mapping_id"],
      ["account_mappings.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("account_mapping_id", "pluggy_transaction_id", name="uq_account_pluggy_transaction"),
    sa.UniqueConstraint("account_mapping_id", "ynab_transaction_id", name="uq_account_ynab_transaction"),
  )
  op.create_index(op.f("ix_transactions_account_mapping_id"), "transactions", ["account_mapping_id"], unique=False)
  op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
  op.create_index(
    op.f("ix_transactions_pluggy_transaction_id"), "transactions", ["pluggy_transaction_id"], unique=False
  )
  op.create_index(op.f("ix_transactions_synced_at"), "transactions", ["synced_at"], unique=False)
  op.create_index(op.f("ix_transactions_ynab_transaction_id"), "transactions", ["ynab_transaction_id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_transactions_ynab_transaction_id"), table_name="transactions")
  op.drop_index(op.f("ix_transactions_synced_at"), table_name="transactions")
  op.drop_index(op.f("ix_transactions_pluggy_transaction_id"), table_name="transactions")
  op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
  op.drop_index(op.f("ix_transactions_account_mapping_id"), table_name="transactions")
  op.drop_table("transactions")
  # ### end Alembic commands ###
