"""Add new fields to account reference

Revision ID: 7feac44bd192
Revises: a92e1abcd306
Create Date: 2024-10-09 20:34:07.283981

"""

import sqlalchemy as sa
import sqlmodel  # New
from alembic import op

# revision identifiers, used by Alembic.
revision = "7feac44bd192"
down_revision = "a92e1abcd306"
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "account_references",
    sa.Column("external_destination_budget_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
  )
  op.add_column(
    "account_references", sa.Column("external_destination_payee_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
  )
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("account_references", "external_destination_payee_id")
  op.drop_column("account_references", "external_destination_budget_id")
  # ### end Alembic commands ###
