"""Added accounts table

Revision ID: a46ee198495e
Revises:
Create Date: 2025-05-17 16:27:52.046267

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a46ee198495e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "account_mappings",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column(
      "account_type",
      sa.Enum("CHECKING", "SAVINGS", "CREDIT_CARD", "INVESTMENT", "LOAN", "OTHER", name="accountmappingtype"),
      nullable=False,
    ),
    sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", "ARCHIVED", name="accountmappingstatus"), nullable=False),
    sa.Column("pluggy_item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("pluggy_account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("ynab_account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("ynab_budget_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_account_mappings_id"), "account_mappings", ["id"], unique=False)
  op.create_index(op.f("ix_account_mappings_name"), "account_mappings", ["name"], unique=False)
  op.create_index(op.f("ix_account_mappings_pluggy_account_id"), "account_mappings", ["pluggy_account_id"], unique=True)
  op.create_index(op.f("ix_account_mappings_pluggy_item_id"), "account_mappings", ["pluggy_item_id"], unique=False)
  op.create_index(op.f("ix_account_mappings_ynab_account_id"), "account_mappings", ["ynab_account_id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_account_mappings_ynab_account_id"), table_name="account_mappings")
  op.drop_index(op.f("ix_account_mappings_pluggy_item_id"), table_name="account_mappings")
  op.drop_index(op.f("ix_account_mappings_pluggy_account_id"), table_name="account_mappings")
  op.drop_index(op.f("ix_account_mappings_name"), table_name="account_mappings")
  op.drop_index(op.f("ix_account_mappings_id"), table_name="account_mappings")
  op.drop_table("account_mappings")
  # ### end Alembic commands ###
