"""Add account reference

Revision ID: a92e1abcd306
Revises: 77375510cc34
Create Date: 2024-10-07 20:33:19.891935

"""

import sqlalchemy as sa
import sqlmodel  # New
from alembic import op

# revision identifiers, used by Alembic.
revision = "a92e1abcd306"
down_revision = "77375510cc34"
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "account_references",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("external_source_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("external_destination_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("user_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(
      ["user_id"],
      ["users.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    op.f("ix_account_references_external_destination_id"),
    "account_references",
    ["external_destination_id"],
    unique=False,
  )
  op.create_index(
    op.f("ix_account_references_external_source_id"), "account_references", ["external_source_id"], unique=False
  )
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_account_references_external_source_id"), table_name="account_references")
  op.drop_index(op.f("ix_account_references_external_destination_id"), table_name="account_references")
  op.drop_table("account_references")
  # ### end Alembic commands ###
