"""Added accounts table

Revision ID: f5b7a202fc33
Revises:
Create Date: 2025-05-17 15:33:09.190187

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5b7a202fc33"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  op.create_table(
    "account_mappings",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column(
      "account_type",
      sa.Enum("CHECKING", "SAVINGS", "CREDIT_CARD", "INVESTMENT", "LOAN", "OTHER", name="account_mapping_type"),
      nullable=False,
    ),
    sa.Column(
      "status",
      sa.Enum("ACTIVE", "INACTIVE", "ARCHIVED", name="account_mapping_status"),
      nullable=False,
      server_default="INACTIVE",
    ),
    sa.Column("pluggy_item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("pluggy_account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("ynab_account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("ynab_budget_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("idx_acm_id"), "account_mappings", ["id"], unique=False)
  op.create_index(op.f("idx_acm_name"), "account_mappings", ["name"], unique=False)
  op.create_index(op.f("idx_acm_pluggy_account_id"), "account_mappings", ["pluggy_account_id"], unique=True)
  op.create_index(op.f("idx_acm_pluggy_item_id"), "account_mappings", ["pluggy_item_id"], unique=False)
  op.create_index(op.f("idx_acm_ynab_account_id"), "account_mappings", ["ynab_account_id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("idx_acm_ynab_account_id"), table_name="account_mappings")
  op.drop_index(op.f("idx_acm_pluggy_item_id"), table_name="account_mappings")
  op.drop_index(op.f("idx_acm_pluggy_account_id"), table_name="account_mappings")
  op.drop_index(op.f("idx_acm_name"), table_name="account_mappings")
  op.drop_index(op.f("idx_acm_id"), table_name="account_mappings")
  op.drop_table("account_mappings")
  # ### end Alembic commands ###
